# Generated by Django 4.2 on 2024-12-06 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssembledAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('assembly_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembled_aircraft', to='parts.aircraft')),
                ('assembly_team', models.ForeignKey(limit_choices_to={'team_type': 'ASSEMBLY'}, on_delete=django.db.models.deletion.PROTECT, to='teams.team')),
                ('avionics', models.OneToOneField(limit_choices_to={'is_used': False, 'part_type': 'AVIONICS'}, on_delete=django.db.models.deletion.PROTECT, related_name='assembled_as_avionics', to='parts.part')),
                ('fuselage', models.OneToOneField(limit_choices_to={'is_used': False, 'part_type': 'FUSELAGE'}, on_delete=django.db.models.deletion.PROTECT, related_name='assembled_as_fuselage', to='parts.part')),
                ('tail', models.OneToOneField(limit_choices_to={'is_used': False, 'part_type': 'TAIL'}, on_delete=django.db.models.deletion.PROTECT, related_name='assembled_as_tail', to='parts.part')),
                ('wing', models.OneToOneField(limit_choices_to={'is_used': False, 'part_type': 'WING'}, on_delete=django.db.models.deletion.PROTECT, related_name='assembled_as_wing', to='parts.part')),
            ],
            options={
                'verbose_name': 'Assembled Aircraft',
                'verbose_name_plural': 'Assembled Aircraft',
                'ordering': ['-assembly_date'],
            },
        ),
    ]
