# Generated by Django 4.2 on 2024-12-10 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssembledAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembled_aircraft', to='parts.aircraft')),
                ('assembly_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembled_aircraft', to='teams.team')),
                ('parts', models.ManyToManyField(related_name='assembled_in', to='parts.part')),
            ],
            options={
                'verbose_name': 'Assembled Aircraft',
                'verbose_name_plural': 'Assembled Aircraft',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('WING_PRODUCTION', 'Wing Production'), ('FUSELAGE_PRODUCTION', 'Fuselage Production'), ('TAIL_PRODUCTION', 'Tail Production'), ('AVIONICS_PRODUCTION', 'Avionics Production'), ('QUALITY_CHECK', 'Quality Check'), ('ASSEMBLY', 'Assembly'), ('TESTING', 'Testing'), ('FINAL_CHECK', 'Final Check')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembled_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='assembly.assembledaircraft')),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_steps', to='teams.team')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'ordering': ['created_at'],
            },
        ),
    ]
