# Generated by Django 4.2 on 2024-12-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembledaircraft',
            name='parts',
            field=models.ManyToManyField(related_name='assembled_in', to='parts.part', verbose_name='Used Parts'),
        ),
    ]
