# Generated by Django 4.2 on 2024-12-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('wing', 'Wing Team'), ('fuselage', 'Fuselage Team'), ('tail', 'Tail Team'), ('avionics', 'Avionics Team'), ('assembly', 'Assembly Team')], max_length=20),
        ),
    ]
